#:schema node_modules/wrangler/config-schema.json
name = "grok-playground"
main = "src/index.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./src/static" }

[observability]
enabled = true

